package com.bapseguen.app.dto;

public class BannerDTO {
//	CREATE TABLE TBL_BANNER (
//			  BANNER_NUMBER  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  BANNER_TITLE          VARCHAR2(200) NOT NULL,
//			  IMAGE_NUMBER   NUMBER
//			                   CONSTRAINT FK_BANNER_IMAGE
//			                   REFERENCES TBL_IMAGE(POST_IMAGE_NUMBER),
//			  BANNER_LINK_URL       VARCHAR2(500),
//			  BANNER_START_DATE     DATE NOT NULL,
//			  BANNER_END_DATE       DATE NOT NULL,
//			  BANNER_IS_ACTIVE      CHAR(1) DEFAULT 'Y' NOT NULL
//			                   CONSTRAINT CK_BANNER_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
//			  BANNER_CREATED_BY     NUMBER
//			                   CONSTRAINT FK_BANNER_ADMIN
//			                   REFERENCES TBL_ADMIN(MEMBER_NUMBER),
//			  BANNER_CREATED_DATE   DATE DEFAULT SYSDATE NOT NULL,
//			  BANNER_UPDATED_DATE   DATE
//			);
	private int bannerNumber;
	private String bannerTitle;
	private int imageNumber;
	private String bannerLinkUrl;
	private String bannerStartDate;
	private String bannerEndDate;
	private boolean bannerIsActive;
	private int bannerCreatedBy;
	private String bannerCreatedDate;
	private String bannerUpdatedDate;
	public int getBannerNumber() {
		return bannerNumber;
	}
	public void setBannerNumber(int bannerNumber) {
		this.bannerNumber = bannerNumber;
	}
	public String getBannerTitle() {
		return bannerTitle;
	}
	public void setBannerTitle(String bannerTitle) {
		this.bannerTitle = bannerTitle;
	}
	public int getImageNumber() {
		return imageNumber;
	}
	public void setImageNumber(int imageNumber) {
		this.imageNumber = imageNumber;
	}
	public String getBannerLinkUrl() {
		return bannerLinkUrl;
	}
	public void setBannerLinkUrl(String bannerLinkUrl) {
		this.bannerLinkUrl = bannerLinkUrl;
	}
	public String getBannerStartDate() {
		return bannerStartDate;
	}
	public void setBannerStartDate(String bannerStartDate) {
		this.bannerStartDate = bannerStartDate;
	}
	public String getBannerEndDate() {
		return bannerEndDate;
	}
	public void setBannerEndDate(String bannerEndDate) {
		this.bannerEndDate = bannerEndDate;
	}
	public boolean isBannerIsActive() {
		return bannerIsActive;
	}
	public void setBannerIsActive(boolean bannerIsActive) {
		this.bannerIsActive = bannerIsActive;
	}
	public int getBannerCreatedBy() {
		return bannerCreatedBy;
	}
	public void setBannerCreatedBy(int bannerCreatedBy) {
		this.bannerCreatedBy = bannerCreatedBy;
	}
	public String getBannerCreatedDate() {
		return bannerCreatedDate;
	}
	public void setBannerCreatedDate(String bannerCreatedDate) {
		this.bannerCreatedDate = bannerCreatedDate;
	}
	public String getBannerUpdatedDate() {
		return bannerUpdatedDate;
	}
	public void setBannerUpdatedDate(String bannerUpdatedDate) {
		this.bannerUpdatedDate = bannerUpdatedDate;
	}
	@Override
	public String toString() {
		return "BannerDTO [bannerNumber=" + bannerNumber + ", bannerTitle=" + bannerTitle + ", imageNumber="
				+ imageNumber + ", bannerLinkUrl=" + bannerLinkUrl + ", bannerStartDate=" + bannerStartDate
				+ ", bannerEndDate=" + bannerEndDate + ", bannerIsActive=" + bannerIsActive + ", bannerCreatedBy="
				+ bannerCreatedBy + ", bannerCreatedDate=" + bannerCreatedDate + ", bannerUpdatedDate="
				+ bannerUpdatedDate + "]";
	}

	
	
	
	
	
	
}
