package com.bapseguen.app.dto;

public class BoardDTO {
//	CREATE TABLE TBL_BOARD (
//		  	  BOARD_NUMBER  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  BOARD_TYPE    VARCHAR2(50) NOT NULL
//			                  CONSTRAINT UQ_BOARD_TYPE UNIQUE,
//			  BOARD_TAG_NAME      VARCHAR2(50)
//			);
	private int boardNumber;
	private String boardType;
	private String boardTagName;
	public int getBoardNumber() {
		return boardNumber;
	}
	public void setBoardNumber(int boardNumber) {
		this.boardNumber = boardNumber;
	}
	public String getBoardType() {
		return boardType;
	}
	public void setBoardType(String boardType) {
		this.boardType = boardType;
	}
	public String getBoardTagName() {
		return boardTagName;
	}
	public void setBoardTagName(String boardTagName) {
		this.boardTagName = boardTagName;
	}
	@Override
	public String toString() {
		return "BoardDTO [boardNumber=" + boardNumber + ", boardType=" + boardType + ", boardTagName=" + boardTagName
				+ "]";
	}

	
	
}
