package com.bapseguen.app.dto;

import java.util.List;

public class CartDTO {
//	CREATE TABLE TBL_CART (
//			  CART_NUMBER     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  MEMBER_NUMBER   NUMBER
//			                    CONSTRAINT FK_CART_MEMBER
//			                    REFERENCES TBL_MEMBER(MEMBER_NUMBER) ON DELETE CASCADE,
//			  BUSINESS_NUMBER VARCHAR2(50) NOT NULL
//			                    CONSTRAINT FK_CART_STORE
//			                    REFERENCES TBL_STORE(BUSINESS_NUMBER) ON DELETE CASCADE,
//			  CART_ORDER_STATUS    VARCHAR2(20)
//			                    CONSTRAINT CK_CART_STATUS CHECK (ORDER_STATUS IN ('OPEN','ORDERED','CANCELLED')),
//			  ORDER_NUMBER    NUMBER
//			                    CONSTRAINT FK_CART_ORDER
//			                    REFERENCES TBL_ORDERS(ORDER_NUMBER) ON DELETE SET NULL
//			);
	private int cartNumber; // CART_NUMBER
	private int memberNumber; // MEMBER_NUMBER
	private String businessNumber; // BUSINESS_NUMBER
	private String cartOrderStatus; // ORDER_STATUS (OPEN, ORDERED, CANCELLED)
	private Integer orderNumber; // 연결된 주문번호 (결제 완료시)
	private List<CartItemDTO> items; // 장바구니 아이템 리스트
	public int getCartNumber() {
		return cartNumber;
	}
	public void setCartNumber(int cartNumber) {
		this.cartNumber = cartNumber;
	}
	public int getMemberNumber() {
		return memberNumber;
	}
	public void setMemberNumber(int memberNumber) {
		this.memberNumber = memberNumber;
	}
	public String getBusinessNumber() {
		return businessNumber;
	}
	public void setBusinessNumber(String businessNumber) {
		this.businessNumber = businessNumber;
	}
	public String getCartOrderStatus() {
		return cartOrderStatus;
	}
	public void setCartOrderStatus(String cartOrderStatus) {
		this.cartOrderStatus = cartOrderStatus;
	}
	public Integer getOrderNumber() {
		return orderNumber;
	}
	public void setOrderNumber(Integer orderNumber) {
		this.orderNumber = orderNumber;
	}
	public List<CartItemDTO> getItems() {
		return items;
	}
	public void setItems(List<CartItemDTO> items) {
		this.items = items;
	}
	@Override
	public String toString() {
		return "CartDTO [cartNumber=" + cartNumber + ", memberNumber=" + memberNumber + ", businessNumber="
				+ businessNumber + ", cartOrderStatus=" + cartOrderStatus + ", orderNumber=" + orderNumber + ", items="
				+ items + "]";
	}
	

	
	
}
