package com.bapseguen.app.dto;

public class CartItemDTO {
//	CREATE TABLE TBL_CART_ITEM (
//			  CART_ITEM_NUMBER  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  CART_NUMBER       NUMBER
//			                      CONSTRAINT FK_CITEM_CART
//			                      REFERENCES TBL_CART(CART_NUMBER) ON DELETE CASCADE,
//			  ITEM_NUMBER       NUMBER
//			                      CONSTRAINT FK_CITEM_ITEM
//			                      REFERENCES TBL_ITEM(ITEM_NUMBER) ON DELETE CASCADE,
//			  CART_ITEM_UNIT_PRICE        NUMBER NOT NULL,
//			  CART_ITEM_QUANTITY          NUMBER NOT NULL
//			);
    private int cartItemNumber;  // 장바구니 아이템 번호
    private int cartNumber;      // 장바구니 번호
    private int itemNumber;      // 상품 번호
    private int cartItemUnitPrice;       // 단가
    private int cartItemQuantity;        // 수량
	public int getCartItemNumber() {
		return cartItemNumber;
	}
	public void setCartItemNumber(int cartItemNumber) {
		this.cartItemNumber = cartItemNumber;
	}
	public int getCartNumber() {
		return cartNumber;
	}
	public void setCartNumber(int cartNumber) {
		this.cartNumber = cartNumber;
	}
	public int getItemNumber() {
		return itemNumber;
	}
	public void setItemNumber(int itemNumber) {
		this.itemNumber = itemNumber;
	}
	public int getCartItemUnitPrice() {
		return cartItemUnitPrice;
	}
	public void setCartItemUnitPrice(int cartItemUnitPrice) {
		this.cartItemUnitPrice = cartItemUnitPrice;
	}
	public int getCartItemQuantity() {
		return cartItemQuantity;
	}
	public void setCartItemQuantity(int cartItemQuantity) {
		this.cartItemQuantity = cartItemQuantity;
	}
	@Override
	public String toString() {
		return "CartItemDTO [cartItemNumber=" + cartItemNumber + ", cartNumber=" + cartNumber + ", itemNumber="
				+ itemNumber + ", cartItemUnitPrice=" + cartItemUnitPrice + ", cartItemQuantity=" + cartItemQuantity
				+ "]";
	}
    

    
	
}
