package com.bapseguen.app.dto;

public class CommentDTO {
//	CREATE TABLE TBL_COMMENT (
//			  COMMENT_NUMBER  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  POST_NUMBER     NUMBER
//			                    CONSTRAINT FK_COMMENT_POST
//			                    REFERENCES TBL_POST(POST_NUMBER) ON DELETE CASCADE,
//			  MEMBER_NUMBER   NUMBER
//			                    CONSTRAINT FK_COMMENT_MEMBER
//			                    REFERENCES TBL_MEMBER(MEMBER_NUMBER) ON DELETE SET NULL,
//			  COMMENT_CONTENT         VARCHAR2(500),
//			  COMMENTED_DATE  DATE,
//			  COMMENT_DELETE_STATE    CHAR(1) DEFAULT 'N' NOT NULL
//			                    CONSTRAINT CK_COMMENT_DEL CHECK (DELETE_STATE IN ('Y','N'))
//			);
	private int commentNumber;
	private int postNumber;
	private int memberNumber;
	private String comment_content;
	private String commentedDate;
	private boolean commentDeleteState;
	public int getCommentNumber() {
		return commentNumber;
	}
	public void setCommentNumber(int commentNumber) {
		this.commentNumber = commentNumber;
	}
	public int getPostNumber() {
		return postNumber;
	}
	public void setPostNumber(int postNumber) {
		this.postNumber = postNumber;
	}
	public int getMemberNumber() {
		return memberNumber;
	}
	public void setMemberNumber(int memberNumber) {
		this.memberNumber = memberNumber;
	}
	public String getComment_content() {
		return comment_content;
	}
	public void setComment_content(String comment_content) {
		this.comment_content = comment_content;
	}
	public String getCommentedDate() {
		return commentedDate;
	}
	public void setCommentedDate(String commentedDate) {
		this.commentedDate = commentedDate;
	}
	public boolean isCommentDeleteState() {
		return commentDeleteState;
	}
	public void setCommentDeleteState(boolean commentDeleteState) {
		this.commentDeleteState = commentDeleteState;
	}
	@Override
	public String toString() {
		return "CommentDTO [commentNumber=" + commentNumber + ", postNumber=" + postNumber + ", memberNumber="
				+ memberNumber + ", comment_content=" + comment_content + ", commentedDate=" + commentedDate
				+ ", commentDeleteState=" + commentDeleteState + "]";
	}
	
}
