package com.bapseguen.app.dto;

public class InquiryDTO {
//	CREATE TABLE TBL_INQUIRY (
//			  INQUIRY_NUMBER        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  MEMBER_NUMBER         NUMBER
//			                          CONSTRAINT FK_INQ_MEMBER
//			                          REFERENCES TBL_MEMBER(MEMBER_NUMBER) ON DELETE SET NULL,
//			  INQUIRY_TITLE         VARCHAR2(200) NOT NULL,
//			  INQUIRY_CONTENT       CLOB NOT NULL,
//			  INQUIRY_SCOPE         VARCHAR2(50),
//			  INQUIRY_STATUS        VARCHAR2(20)
//			                          CONSTRAINT CK_INQ_STATUS CHECK (INQUIRY_STATUS IN ('YET','IN_PROGRESS','COMPLETE')),
//			  INQUIRY_CREATED_DATE  DATE,
//			  INQUIRY_TAG_NAME      VARCHAR2(50)
//			);
	
	private int inquiryNumber;
	private int memberNumber;
	private String inquiryTitle;
	private String inquiryContent;
	private String inquiryScope;
	private String inquiryStatus;
	private String inquiryCreatedDate;
	private String inquiryTagName;
	public int getInquiryNumber() {
		return inquiryNumber;
	}
	public void setInquiryNumber(int inquiryNumber) {
		this.inquiryNumber = inquiryNumber;
	}
	public int getMemberNumber() {
		return memberNumber;
	}
	public void setMemberNumber(int memberNumber) {
		this.memberNumber = memberNumber;
	}
	public String getInquiryTitle() {
		return inquiryTitle;
	}
	public void setInquiryTitle(String inquiryTitle) {
		this.inquiryTitle = inquiryTitle;
	}
	public String getInquiryContent() {
		return inquiryContent;
	}
	public void setInquiryContent(String inquiryContent) {
		this.inquiryContent = inquiryContent;
	}
	public String getInquiryScope() {
		return inquiryScope;
	}
	public void setInquiryScope(String inquiryScope) {
		this.inquiryScope = inquiryScope;
	}
	public String getInquiryStatus() {
		return inquiryStatus;
	}
	public void setInquiryStatus(String inquiryStatus) {
		this.inquiryStatus = inquiryStatus;
	}
	public String getInquiryCreatedDate() {
		return inquiryCreatedDate;
	}
	public void setInquiryCreatedDate(String inquiryCreatedDate) {
		this.inquiryCreatedDate = inquiryCreatedDate;
	}
	public String getInquiryTagName() {
		return inquiryTagName;
	}
	public void setInquiryTagName(String inquiryTagName) {
		this.inquiryTagName = inquiryTagName;
	}
	@Override
	public String toString() {
		return "InquiryDTO [inquiryNumber=" + inquiryNumber + ", memberNumber=" + memberNumber + ", inquiryTitle="
				+ inquiryTitle + ", inquiryContent=" + inquiryContent + ", inquiryScope=" + inquiryScope
				+ ", inquiryStatus=" + inquiryStatus + ", inquiryCreatedDate=" + inquiryCreatedDate
				+ ", inquiryTagName=" + inquiryTagName + "]";
	}
	
}
