package com.bapseguen.app.dto;

public class InquiryCommentDTO {
//	CREATE TABLE TBL_INQUIRY_COMMENT (
//			  INQUIRY_COMMENT_NUMBER  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  INQUIRY_NUMBER          NUMBER
//			                            CONSTRAINT FK_INQC_INQ
//			                            REFERENCES TBL_INQUIRY(INQUIRY_NUMBER) ON DELETE CASCADE,
//			  MEMBER_NUMBER           NUMBER
//			                            CONSTRAINT FK_INQC_ADMIN
//			                            REFERENCES TBL_ADMIN(MEMBER_NUMBER) ON DELETE SET NULL,
//			  INQUIRY_COMMENT_CONTENT VARCHAR2(500),
//			  INQUIRY_COMMENT_CREATED_DATE    DATE
//			);

	private int inquiryCommentNumber;
	private int inquiryNumber;
	private int memberNumber;
	private String inquiryCommentContent;
	private String inquiryCommentCreatedDate;
	public int getInquiryCommentNumber() {
		return inquiryCommentNumber;
	}
	public void setInquiryCommentNumber(int inquiryCommentNumber) {
		this.inquiryCommentNumber = inquiryCommentNumber;
	}
	public int getInquiryNumber() {
		return inquiryNumber;
	}
	public void setInquiryNumber(int inquiryNumber) {
		this.inquiryNumber = inquiryNumber;
	}
	public int getMemberNumber() {
		return memberNumber;
	}
	public void setMemberNumber(int memberNumber) {
		this.memberNumber = memberNumber;
	}
	public String getInquiryCommentContent() {
		return inquiryCommentContent;
	}
	public void setInquiryCommentContent(String inquiryCommentContent) {
		this.inquiryCommentContent = inquiryCommentContent;
	}
	public String getInquiryCommentCreatedDate() {
		return inquiryCommentCreatedDate;
	}
	public void setInquiryCommentCreatedDate(String inquiryCommentCreatedDate) {
		this.inquiryCommentCreatedDate = inquiryCommentCreatedDate;
	}
	@Override
	public String toString() {
		return "InquiryCommentDTO [inquiryCommentNumber=" + inquiryCommentNumber + ", inquiryNumber=" + inquiryNumber
				+ ", memberNumber=" + memberNumber + ", inquiryCommentContent=" + inquiryCommentContent
				+ ", inquiryCommentCreatedDate=" + inquiryCommentCreatedDate + "]";
	}
	
	
}
