package com.bapseguen.app.dto;

public class ItemDTO {
//	CREATE TABLE TBL_ITEM (
//			  ITEM_NUMBER    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  BUSINESS_NUMBER VARCHAR2(50)
//			                    CONSTRAINT FK_ITEM_STORE
//			                    REFERENCES TBL_STORE(BUSINESS_NUMBER),
//			  ITEM_TYPE      VARCHAR2(20)
//			                    CONSTRAINT CK_ITEM_TYPE CHECK (ITEM_TYPE IN ('FOOD','INGREDIENT')),
//			  ITEM_NAME      VARCHAR2(100) NOT NULL,
//			  ITEM_PRICE          NUMBER NOT NULL,
//			  ITEM_QUANTITY       NUMBER,
//			  ITEM_ORIGIN         VARCHAR2(100),
//			  ITEM_EXPIRE_DATE    DATE NOT NULL
//			);
	
	private int itemNumber;
	private String businessNumber;
	private String itemType;
	private String itemName;
	private int itemPrice;
	private int itemQuantity;
	private String itemOrigin;
	private String itemExpireDate;
	
	
	public int getItemNumber() {
		return itemNumber;
	}
	public void setItemNumber(int itemNumber) {
		this.itemNumber = itemNumber;
	}
	public String getBusinessNumber() {
		return businessNumber;
	}
	public void setBusinessNumber(String businessNumber) {
		this.businessNumber = businessNumber;
	}
	public String getItemType() {
		return itemType;
	}
	public void setItemType(String itemType) {
		this.itemType = itemType;
	}
	public String getItemName() {
		return itemName;
	}
	public void setItemName(String itemName) {
		this.itemName = itemName;
	}
	public int getItemPrice() {
		return itemPrice;
	}
	public void setItemPrice(int itemPrice) {
		this.itemPrice = itemPrice;
	}
	public int getItemQuantity() {
		return itemQuantity;
	}
	public void setItemQuantity(int itemQuantity) {
		this.itemQuantity = itemQuantity;
	}
	public String getItemOrigin() {
		return itemOrigin;
	}
	public void setItemOrigin(String itemOrigin) {
		this.itemOrigin = itemOrigin;
	}
	public String getItemExpireDate() {
		return itemExpireDate;
	}
	public void setItemExpireDate(String itemExpireDate) {
		this.itemExpireDate = itemExpireDate;
	}
	@Override
	public String toString() {
		return "ItemDTO [itemNumber=" + itemNumber + ", businessNumber=" + businessNumber + ", itemType=" + itemType
				+ ", itemName=" + itemName + ", itemPrice=" + itemPrice + ", itemQuantity=" + itemQuantity
				+ ", itemOrigin=" + itemOrigin + ", itemExpireDate=" + itemExpireDate + "]";
	}
	
	
}
