package com.bapseguen.app.dto;

import java.util.List;

public class OrdersDTO {
//	CREATE TABLE TBL_ORDERS (
//			  ORDER_NUMBER    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  MEMBER_NUMBER   NUMBER
//			                    CONSTRAINT FK_ORDERS_MEMBER
//			                    REFERENCES TBL_MEMBER(MEMBER_NUMBER) ON DELETE SET NULL,
//			  ORDERS_PAYMENT_INFO    VARCHAR2(200),
//			  ORDERS_DATE      DATE NOT NULL,
//			  ORDERS_TOTAL_AMOUNT    NUMBER,
//			  ORDERS_PAYMENT_STATUS  VARCHAR2(20)
//			);
    private int orderNumber;
    private int memberNumber;
    private String ordersPaymentInfo;
    private String orderDate;
    private int ordersTotalAmount;
    private String ordersPaymentStatus;
    private List<OrderItemDTO> items; // 주문 항목
	public int getOrderNumber() {
		return orderNumber;
	}
	public void setOrderNumber(int orderNumber) {
		this.orderNumber = orderNumber;
	}
	public int getMemberNumber() {
		return memberNumber;
	}
	public void setMemberNumber(int memberNumber) {
		this.memberNumber = memberNumber;
	}
	public String getOrdersPaymentInfo() {
		return ordersPaymentInfo;
	}
	public void setOrdersPaymentInfo(String ordersPaymentInfo) {
		this.ordersPaymentInfo = ordersPaymentInfo;
	}
	public String getOrderDate() {
		return orderDate;
	}
	public void setOrderDate(String orderDate) {
		this.orderDate = orderDate;
	}
	public int getOrdersTotalAmount() {
		return ordersTotalAmount;
	}
	public void setOrdersTotalAmount(int ordersTotalAmount) {
		this.ordersTotalAmount = ordersTotalAmount;
	}
	public String getOrdersPaymentStatus() {
		return ordersPaymentStatus;
	}
	public void setOrdersPaymentStatus(String ordersPaymentStatus) {
		this.ordersPaymentStatus = ordersPaymentStatus;
	}
	public List<OrderItemDTO> getItems() {
		return items;
	}
	public void setItems(List<OrderItemDTO> items) {
		this.items = items;
	}
	@Override
	public String toString() {
		return "OrdersDTO [orderNumber=" + orderNumber + ", memberNumber=" + memberNumber + ", ordersPaymentInfo="
				+ ordersPaymentInfo + ", orderDate=" + orderDate + ", ordersTotalAmount=" + ordersTotalAmount
				+ ", ordersPaymentStatus=" + ordersPaymentStatus + ", items=" + items + "]";
	}

	
}
