package com.bapseguen.app.dto;

import java.util.List;

public class OrdersDTO {
//	CREATE TABLE TBL_ORDERS (
//			  ORDERS_NUMBER    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  ORDERS_MEMBER_NUMBER   NUMBER
//			                    CONSTRAINT FK_ORDERS_MEMBER
//			                    REFERENCES TBL_MEMBER(MEMBER_NUMBER) ON DELETE SET NULL,
//			  ORDERS_PAYMENT_INFO    VARCHAR2(200),
//			  ORDERS_DATE      DATE NOT NULL,
//			  ORDERS_TOTAL_AMOUNT    NUMBER,
//			  ORDERS_PAYMENT_STATUS  VARCHAR2(20)
//			);
    private int ordersNumber; // 주문 번호
    private int ordersMemberNumber; // 주문자 회원 번호
    private String ordersPaymentInfo; //  (???)
    private String ordersDate; // 주문 날짜
    private int ordersTotalAmount; // 주문 금액
    private String ordersPaymentStatus; // 주문 상태(???)
    private List<OrderItemDTO> items; // 주문 항목
	public int getOrdersNumber() {
		return ordersNumber;
	}
	public void setOrdersNumber(int ordersNumber) {
		this.ordersNumber = ordersNumber;
	}
	public int getOrdersMemberNumber() {
		return ordersMemberNumber;
	}
	public void setOrdersMemberNumber(int ordersMemberNumber) {
		this.ordersMemberNumber = ordersMemberNumber;
	}
	public String getOrdersPaymentInfo() {
		return ordersPaymentInfo;
	}
	public void setOrdersPaymentInfo(String ordersPaymentInfo) {
		this.ordersPaymentInfo = ordersPaymentInfo;
	}
	public String getOrdersDate() {
		return ordersDate;
	}
	public void setOrdersDate(String ordersDate) {
		this.ordersDate = ordersDate;
	}
	public int getOrdersTotalAmount() {
		return ordersTotalAmount;
	}
	public void setOrdersTotalAmount(int ordersTotalAmount) {
		this.ordersTotalAmount = ordersTotalAmount;
	}
	public String getOrdersPaymentStatus() {
		return ordersPaymentStatus;
	}
	public void setOrdersPaymentStatus(String ordersPaymentStatus) {
		this.ordersPaymentStatus = ordersPaymentStatus;
	}
	public List<OrderItemDTO> getItems() {
		return items;
	}
	public void setItems(List<OrderItemDTO> items) {
		this.items = items;
	}
	
	@Override
	public String toString() {
		return "OrdersDTO [ordersNumber=" + ordersNumber + ", ordersMemberNumber=" + ordersMemberNumber
				+ ", ordersPaymentInfo=" + ordersPaymentInfo + ", ordersDate=" + ordersDate + ", ordersTotalAmount="
				+ ordersTotalAmount + ", ordersPaymentStatus=" + ordersPaymentStatus + ", items=" + items + "]";
	}
	
	
    
    
}
