package com.bapseguen.app.dto;

public class OrderItemDTO {
//	CREATE TABLE TBL_ORDER_ITEM (
//			  ORDER_ITEM_NUMBER  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  ORDER_NUMBER       NUMBER
//			                       CONSTRAINT FK_OITEM_ORDER
//			                       REFERENCES TBL_ORDERS(ORDER_NUMBER) ON DELETE CASCADE,
//			  ITEM_NUMBER        NUMBER
//			                       CONSTRAINT FK_OITEM_ITEM
//			                       REFERENCES TBL_ITEM(ITEM_NUMBER),
//			  ORDER_ITEM_UNIT_PRICE         NUMBER NOT NULL,
//			  ORDER_ITEM_QUANTITY           NUMBER NOT NULL
//			);
	private int orderItemNumber; // ORDER_ITEM_NUMBER
	private int orderNumber;
	private int itemNumber; // ITEM_NUMBER
	private int orderItemUnitPrice; // UNIT_PRICE
	private int orderItemQuantity; // QUANTITY
	public int getOrderItemNumber() {
		return orderItemNumber;
	}
	public void setOrderItemNumber(int orderItemNumber) {
		this.orderItemNumber = orderItemNumber;
	}
	public int getOrderNumber() {
		return orderNumber;
	}
	public void setOrderNumber(int orderNumber) {
		this.orderNumber = orderNumber;
	}
	public int getItemNumber() {
		return itemNumber;
	}
	public void setItemNumber(int itemNumber) {
		this.itemNumber = itemNumber;
	}
	public int getOrderItemUnitPrice() {
		return orderItemUnitPrice;
	}
	public void setOrderItemUnitPrice(int orderItemUnitPrice) {
		this.orderItemUnitPrice = orderItemUnitPrice;
	}
	public int getOrderItemQuantity() {
		return orderItemQuantity;
	}
	public void setOrderItemQuantity(int orderItemQuantity) {
		this.orderItemQuantity = orderItemQuantity;
	}
	
	@Override
	public String toString() {
		return "OrderItemDTO [orderItemNumber=" + orderItemNumber + ", orderNumber=" + orderNumber + ", itemNumber="
				+ itemNumber + ", orderItemUnitPrice=" + orderItemUnitPrice + ", orderItemQuantity=" + orderItemQuantity
				+ "]";
	}

	
}
