package com.bapseguen.app.dto;

public class PostImageDTO {
//	CREATE TABLE TBL_IMAGE (
//			  IMAGE_NUMBER       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  IMAGE_SYSTEM_NAME  VARCHAR2(300),
//			  IMAGE_ORIGINAL_NAME VARCHAR2(300),
//			  MEMBER_NUMBER           NUMBER
//			    CONSTRAINT FK_IMAGE_MEMBER REFERENCES TBL_MEMBER(MEMBER_NUMBER)
//			);
	
	private int imageNumber;
	private String imageSystemName;
	private String imageOriginalName;
	private int member_number;
	public int getImageNumber() {
		return imageNumber;
	}
	public void setImageNumber(int imageNumber) {
		this.imageNumber = imageNumber;
	}
	public String getImageSystemName() {
		return imageSystemName;
	}
	public void setImageSystemName(String imageSystemName) {
		this.imageSystemName = imageSystemName;
	}
	public String getImageOriginalName() {
		return imageOriginalName;
	}
	public void setImageOriginalName(String imageOriginalName) {
		this.imageOriginalName = imageOriginalName;
	}
	public int getMember_number() {
		return member_number;
	}
	public void setMember_number(int member_number) {
		this.member_number = member_number;
	}
	@Override
	public String toString() {
		return "ImageDTO [imageNumber=" + imageNumber + ", imageSystemName=" + imageSystemName + ", imageOriginalName="
				+ imageOriginalName + ", member_number=" + member_number + "]";
	}
	
	
}
