package com.bapseguen.app.dto;

public class PostDTO {
//	CREATE TABLE TBL_POST (
//			  POST_NUMBER    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  BOARD_NUMBER   NUMBER
//			                   CONSTRAINT FK_POST_BOARD
//			                   REFERENCES TBL_BOARD(BOARD_NUMBER),
//			  MEMBER_NUMBER  NUMBER
//			                   CONSTRAINT FK_POST_MEMBER
//			                   REFERENCES TBL_MEMBER(MEMBER_NUMBER) ON DELETE SET NULL,
//			  POST_TITLE          VARCHAR2(200) NOT NULL,
//			  POST_CONTENT        CLOB NOT NULL,
//			  POST_LIKE_COUNT     NUMBER DEFAULT 0 NOT NULL,
//			  POST_VIEW_COUNT     NUMBER DEFAULT 0 NOT NULL,
//			  POST_REPORT_COUNT   NUMBER DEFAULT 0,
//			  POST_DELETE_STATE   CHAR(1) DEFAULT 'N' NOT NULL
//			                   CONSTRAINT CK_POST_DEL CHECK (DELETE_STATE IN ('Y','N')),
//			  POST_CREATED_DATE   DATE,
//			  POST_UPDATED_DATE   DATE
//			  IMAGE_NUMBER 		NUMBER	CONSTRAINT FK_POST_IMAGE
//    									REFERENCES TBL_IMAGE(IMAGE_NUMBER),
//			);
	
	private int postNumber;
	private int boardNumber;
	private int memberNumber;
	private String postTitle;
	private String postContent;
	private int postLikeCount;
	private int postViewCount;
	private int postReportCount;
	private boolean postDeleteState;
	private String postCreatedDate;
	private String postUpdatedDate;
	
	private int imageNumber; // tbl_image의 pk

	public int getPostNumber() {
		return postNumber;
	}

	public void setPostNumber(int postNumber) {
		this.postNumber = postNumber;
	}

	public int getBoardNumber() {
		return boardNumber;
	}

	public void setBoardNumber(int boardNumber) {
		this.boardNumber = boardNumber;
	}

	public int getMemberNumber() {
		return memberNumber;
	}

	public void setMemberNumber(int memberNumber) {
		this.memberNumber = memberNumber;
	}

	public String getPostTitle() {
		return postTitle;
	}

	public void setPostTitle(String postTitle) {
		this.postTitle = postTitle;
	}

	public String getPostContent() {
		return postContent;
	}

	public void setPostContent(String postContent) {
		this.postContent = postContent;
	}

	public int getPostLikeCount() {
		return postLikeCount;
	}

	public void setPostLikeCount(int postLikeCount) {
		this.postLikeCount = postLikeCount;
	}

	public int getPostViewCount() {
		return postViewCount;
	}

	public void setPostViewCount(int postViewCount) {
		this.postViewCount = postViewCount;
	}

	public int getPostReportCount() {
		return postReportCount;
	}

	public void setPostReportCount(int postReportCount) {
		this.postReportCount = postReportCount;
	}

	public boolean isPostDeleteState() {
		return postDeleteState;
	}

	public void setPostDeleteState(boolean postDeleteState) {
		this.postDeleteState = postDeleteState;
	}

	public String getPostCreatedDate() {
		return postCreatedDate;
	}

	public void setPostCreatedDate(String postCreatedDate) {
		this.postCreatedDate = postCreatedDate;
	}

	public String getPostUpdatedDate() {
		return postUpdatedDate;
	}

	public void setPostUpdatedDate(String postUpdatedDate) {
		this.postUpdatedDate = postUpdatedDate;
	}

	public int getImageNumber() {
		return imageNumber;
	}


	public void setImageNumber(int imageNumber) {
		this.imageNumber = imageNumber;
	}

	@Override
	public String toString() {
		return "PostDTO [postNumber=" + postNumber + ", boardNumber=" + boardNumber + ", memberNumber=" + memberNumber
				+ ", postTitle=" + postTitle + ", postContent=" + postContent + ", postLikeCount=" + postLikeCount
				+ ", postViewCount=" + postViewCount + ", postReportCount=" + postReportCount + ", postDeleteState="
				+ postDeleteState + ", postCreatedDate=" + postCreatedDate + ", postUpdatedDate=" + postUpdatedDate
				+ ", imageNumber=" + imageNumber + "]";
	}
	
	
	
	
}
