package com.bapseguen.app.dto;

public class PostReportDTO {
//	CREATE TABLE TBL_MEMBER_REPORT (
//			  POST_REPORT_NUMBER            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  POST_NUMBER              NUMBER
//			                             CONSTRAINT FK_REPORT_POST
//			                             REFERENCES TBL_POST(POST_NUMBER) ON DELETE CASCADE,
//			  POST_REPORT_REASON                   VARCHAR2(10), CHECK (REPORT_REASON IN('ADV','BADWORDS','PORN', 'PERSONAL','ETC'))
//			  POST_REPORT_DATE              DATE,
//			  POST_REPORT_COUNT             NUMBER,
//			  REPORTER_MEMBER_NUMBER   NUMBERORTER
//			                             REFERENCES TBL_MEMBER
//			                             CONSTRAINT FK_MREPORT_REP(MEMBER_NUMBER) ON DELETE SET NULL
//			);
	
	private int postReportNumber;
	private int postNumber;
	private String postReportReason;
	private String postReportDate;
	private int postReportCount;
	private int reporterMemberNumber;
	public int getPostReportNumber() {
		return postReportNumber;
	}
	public void setPostReportNumber(int postReportNumber) {
		this.postReportNumber = postReportNumber;
	}
	public int getPostNumber() {
		return postNumber;
	}
	public void setPostNumber(int postNumber) {
		this.postNumber = postNumber;
	}
	public String getPostReportReason() {
		return postReportReason;
	}
	public void setPostReportReason(String postReportReason) {
		this.postReportReason = postReportReason;
	}
	public String getPostReportDate() {
		return postReportDate;
	}
	public void setPostReportDate(String postReportDate) {
		this.postReportDate = postReportDate;
	}
	public int getPostReportCount() {
		return postReportCount;
	}
	public void setPostReportCount(int postReportCount) {
		this.postReportCount = postReportCount;
	}
	public int getReporterMemberNumber() {
		return reporterMemberNumber;
	}
	public void setReporterMemberNumber(int reporterMemberNumber) {
		this.reporterMemberNumber = reporterMemberNumber;
	}
	@Override
	public String toString() {
		return "PostReportDTO [postReportNumber=" + postReportNumber + ", postNumber=" + postNumber
				+ ", postReportReason=" + postReportReason + ", postReportDate=" + postReportDate + ", postReportCount="
				+ postReportCount + ", reporterMemberNumber=" + reporterMemberNumber + "]";
	}
	
	
	
	
	
}
