package com.bapseguen.app.dto;

public class ReviewDTO {
//	CREATE TABLE TBL_REVIEW (
//			  REVIEW_NUMBER     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  ORDERS_NUMBER NUMBER
//			                      CONSTRAINT FK_REVIEW_ORDERS
//			                      REFERENCES TBL_ORDERS(ORDER_NUMBER),
//			  ITEM_NUMBER       NUMBER
//			                      CONSTRAINT FK_REVIEW_ITEM
//			                      REFERENCES TBL_ITEM(ITEM_NUMBER) ON DELETE SET NULL,
//			  MEMBER_NUMBER     NUMBER
//			                      CONSTRAINT FK_REVIEW_MEMBER
//			                      REFERENCES TBL_MEMBER(MEMBER_NUMBER) ON DELETE SET NULL,
//			  REVIEW_RATING            NUMBER NOT NULL
//			                      CONSTRAINT CK_REVIEW_RATING CHECK (RATING BETWEEN 1 AND 5),
//			  REVIEW_TITLE             VARCHAR2(200) NOT NULL,
//			  REVIEW_CONTENT           CLOB NOT NULL,
//			  REVIEW_CREATE_DATE       DATE DEFAULT SYSDATE NOT NULL,
//			  CONSTRAINT UQ_REVIEW_OITEM UNIQUE (ORDER_ITEM_NUMBER) -- 1주문상품 1리뷰 보장
//			);
	
	private int reviewNumber;
	private int ordersNumber;
	private int itemNumber;
	private int memberNumber;
	private int reviewRating;
	private String reviewTitle;
	private String reviewContent;
	private String reviewCreateDate;
	public int getReviewNumber() {
		return reviewNumber;
	}
	public void setReviewNumber(int reviewNumber) {
		this.reviewNumber = reviewNumber;
	}
	public int getOrdersNumber() {
		return ordersNumber;
	}
	public void setOrdersNumber(int ordersNumber) {
		this.ordersNumber = ordersNumber;
	}
	public int getItemNumber() {
		return itemNumber;
	}
	public void setItemNumber(int itemNumber) {
		this.itemNumber = itemNumber;
	}
	public int getMemberNumber() {
		return memberNumber;
	}
	public void setMemberNumber(int memberNumber) {
		this.memberNumber = memberNumber;
	}
	public int getReviewRating() {
		return reviewRating;
	}
	public void setReviewRating(int reviewRating) {
		this.reviewRating = reviewRating;
	}
	public String getReviewTitle() {
		return reviewTitle;
	}
	public void setReviewTitle(String reviewTitle) {
		this.reviewTitle = reviewTitle;
	}
	public String getReviewContent() {
		return reviewContent;
	}
	public void setReviewContent(String reviewContent) {
		this.reviewContent = reviewContent;
	}
	public String getReviewCreateDate() {
		return reviewCreateDate;
	}
	public void setReviewCreateDate(String reviewCreateDate) {
		this.reviewCreateDate = reviewCreateDate;
	}
	@Override
	public String toString() {
		return "ReviewDTO [reviewNumber=" + reviewNumber + ", ordersNumber=" + ordersNumber + ", itemNumber="
				+ itemNumber + ", memberNumber=" + memberNumber + ", reviewRating=" + reviewRating + ", reviewTitle="
				+ reviewTitle + ", reviewContent=" + reviewContent + ", reviewCreateDate=" + reviewCreateDate + "]";
	}
	
	
}
