package com.bapseguen.app.dto;

public class SalePostDTO {
//	CREATE TABLE TBL_SALE_POST (
//			  SALE_POST_NUMBER  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//			  BUSINESS_NUMBER   VARCHAR2(50)
//			                      CONSTRAINT FK_SPOST_SELLER
//			                      REFERENCES TBL_SELLER_MEMBER(MEMBER_NUMBER) ON DELETE CASCADE,
//			  SALE_POST_TITLE             VARCHAR2(200) NOT NULL,
//			  SALE_POST_CONTENT           CLOB NOT NULL,
//			  SALE_POST_PRICE             NUMBER NOT NULL,
//			  SALE_POST_QUANTITY          NUMBER NOT NULL,
//			  SALE_POST_CATEGORY          VARCHAR2(20)
//			                      CONSTRAINT CK_SPOST_CAT CHECK (CATEGORY IN ('FOOD','INGREDIENT')),
//			  SALE_POST_CREATED_DATE      DATE DEFAULT SYSDATE,
//			  SALE_POST_UPDATED_DATE      DATE,
//			  SALE_POST_DELETE_STATE      CHAR(1) DEFAULT 'N' NOT NULL
//			                      CONSTRAINT CK_SPOST_DEL CHECK (DELETE_STATE IN ('Y','N')),
//			  IMAGE_NUMBER      NUMBER
//			                      CONSTRAINT FK_SPOST_IMAGE
//			                      REFERENCES TBL_IMAGE(IMAGE_NUMBER) ON DELETE SET NULL
//			);
	
	private int salePostNumber;
	private String businessNumber;
	private String salePostTitle;
	private String salePostContent;
	private int salePostPrice;
	private int salePostQuantity;
	private String salePostCategory;
	private String salePostCreatedDate;
	private String salePostUpdatedDate;
	private boolean salePostDeleteState;
	private int imageNumber;
	public int getSalePostNumber() {
		return salePostNumber;
	}
	public void setSalePostNumber(int salePostNumber) {
		this.salePostNumber = salePostNumber;
	}
	public String getBusinessNumber() {
		return businessNumber;
	}
	public void setBusinessNumber(String businessNumber) {
		this.businessNumber = businessNumber;
	}
	public String getSalePostTitle() {
		return salePostTitle;
	}
	public void setSalePostTitle(String salePostTitle) {
		this.salePostTitle = salePostTitle;
	}
	public String getSalePostContent() {
		return salePostContent;
	}
	public void setSalePostContent(String salePostContent) {
		this.salePostContent = salePostContent;
	}
	public int getSalePostPrice() {
		return salePostPrice;
	}
	public void setSalePostPrice(int salePostPrice) {
		this.salePostPrice = salePostPrice;
	}
	public int getSalePostQuantity() {
		return salePostQuantity;
	}
	public void setSalePostQuantity(int salePostQuantity) {
		this.salePostQuantity = salePostQuantity;
	}
	public String getSalePostCategory() {
		return salePostCategory;
	}
	public void setSalePostCategory(String salePostCategory) {
		this.salePostCategory = salePostCategory;
	}
	public String getSalePostCreatedDate() {
		return salePostCreatedDate;
	}
	public void setSalePostCreatedDate(String salePostCreatedDate) {
		this.salePostCreatedDate = salePostCreatedDate;
	}
	public String getSalePostUpdatedDate() {
		return salePostUpdatedDate;
	}
	public void setSalePostUpdatedDate(String salePostUpdatedDate) {
		this.salePostUpdatedDate = salePostUpdatedDate;
	}
	public boolean isSalePostDeleteState() {
		return salePostDeleteState;
	}
	public void setSalePostDeleteState(boolean salePostDeleteState) {
		this.salePostDeleteState = salePostDeleteState;
	}
	public int getImageNumber() {
		return imageNumber;
	}
	public void setImageNumber(int imageNumber) {
		this.imageNumber = imageNumber;
	}
	@Override
	public String toString() {
		return "SalePostDTO [salePostNumber=" + salePostNumber + ", businessNumber=" + businessNumber
				+ ", salePostTitle=" + salePostTitle + ", salePostContent=" + salePostContent + ", salePostPrice="
				+ salePostPrice + ", salePostQuantity=" + salePostQuantity + ", salePostCategory=" + salePostCategory
				+ ", salePostCreatedDate=" + salePostCreatedDate + ", salePostUpdatedDate=" + salePostUpdatedDate
				+ ", salePostDeleteState=" + salePostDeleteState + ", imageNumber=" + imageNumber + "]";
	}
	
	
	
}
